name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ls -l # Liste les fichier du répertoire courant
      - name: Read ./README.md
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./README.md
      - name: cowsay
        id: cowsay_output_id # You want id
        uses: Code-Hex/neo-cowsay-action@v1
        with:
          message: ${{steps.package.outputs.content}}
          cow: 'sodomized'